name: carp3d
channels:
  - pytorch
  - defaults
dependencies:
  - python=3.7
  - numpy
  - matplotlib
  - pandas
  - pillow
  - scikit-learn
  - scipy
  - tensorflow
  - tensorboardx
  - torchvision
  - pip
  - pip:
    - opencv-python

